### ISSUE TITLE
Permission for camera use?

### ISSUE THREAD

**Issue by razmans** [doppelganger9/sample-qrcode-pwa-ionic#2]
Do I need to install the camera plugin to get the camera permission?

**Comment by doppelganger9** [comment]
Hi, 

Could you give a little more context to your issue?
- Are you trying to run this on android/iOS/web?
- Which version of the OS/browser?
- By "plugin" you mean cordova plugin?


### To be more clear about this repository's purpose:
- This sample repo is meant to be a PWA so a website with a native like experience.
- I did not test it as an hybrid app, even though I use Ionic (and Cordova underneath).
- As you'll see, there is no config.xml file, and no Cordova Platform in this repo.
- This is a pure web app. I wanted to test how to achieve a QR Scanner from a pure web site to see if this feature could be done in a PWA. My conclusion is.. **not yet**.

Would you think updating the README with this be of any help for other github users?
